### ISSUE TITLE
Display Raptor Running With User's Velocity

### ISSUE THREAD

**Issue by cyberay01** [cse112-sp20/CalamariCrew#13]
- [x] (Name: Get user's velocity , Estimate: 8 hrs)
- [x] Subtask: Ask user for their initial repo (can be changed later)
- [x] Subtask: Get all milestones associated with that repo
- [x] Subtask: Filter to get the milestone with the soonest deadline
- [x] Subtask: Get all issues assigned to user 
- [x] Subtask: Calculate velocity by dividing number open / total number

**Comment by KenLHua** [comment]
Need Unit test
