### ISSUE TITLE
Display of github issues

### ISSUE THREAD

**Issue by vermar0187** [cse112-sp20/CalamariCrew#49]
Currently on `DEV-MASTER`, it will only show a single issue under the `My Github Issues` list on the home page.

![Screen Shot 2020-05-26 at 7 20 45 PM](https://user-images.githubusercontent.com/6922684/82972909-fc92be00-9f8a-11ea-903f-6aa1f87cd421.jpg)

![Screen Shot 2020-05-26 at 7 20 50 PM](https://user-images.githubusercontent.com/6922684/82972893-f13f9280-9f8a-11ea-801b-152d11b71dc2.jpg)

**Comment by KenLHua** [comment]
Fixed
